language: ruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
    - rvm: rbx-18mode

env:
  - MINITEST_VERSION=
  - MINITEST_VERSION=3.5.0
  - MINITEST_VERSION=2.12.1

rvm:
  - 1.9.3
  - 1.9.2
  - rbx-19mode
  - jruby-19mode
  - 1.8.7
  - ree
  - rbx-18mode
  - jruby-18mode
  - ruby-head
  - jruby-head
